### ISSUE TITLE
Strange training / data iteration behavior 

### ISSUE THREAD

**Issue by tjgalvin** [HITS-AIN/PINK#56] opened 2020-04-28 13:09 UTC
I am currently using the git build Version 2.4.1 Git revision: 9346dd6 and noticed some strange behavior that I am a little unclear on. I thought I would report it here to get some thoughts and keep track. 

I have an image binary with about 21,437 images of the shape `(2, 150, 150)`. Against this image binary file I am training four SOMs with Cartesian layouts of 8x8, 15x15, 25x25 and 35x35. Training is taking place across three rounds with the `unitygaussian` neighbourhood function and the circular euclidean distance statistic regions. The first two training rounds have 180 rotations and 5 iterations across the data, while the third training stage has 360 rotation and 10 iterations across the data (flipping enabled for all). 

Across the four SOMs the first two training stages finish without issue. But for the SOMs with sizes 15x15 and 25x25 SOM the training finished early. The 15x15 SOM finished at 80% and the 25x25 at 40%. 

```
  Data file = EMU_WISE_E95E05_Aegean_Components_Complex_islandNorm_Log_Reprojected.bin
  Result file = SOM_B3Circular_h15_w15_emu.bin
  Number of data entries = 21437
  Data dimension = 2 x 150 x 150
  SOM dimension (width x height x depth) = 15x15x1
  SOM size = 225
  Number of iterations = 10
  Neuron dimension = 213x213
  Euclidean distance dimension = 150
  Data type for euclidean distance calculation = uint8
  Shape of euclidean distance region = circular
  Maximal number of progress information prints = 10
  Intermediate storage of SOM = keep
  Layout = cartesian
  Initialization type = file_init
  SOM initialization file = SOM_B2Circular_h15_w15_emu.bin
  Interpolation type = bilinear
  Seed = 1234
  Number of rotations = 360
  Use mirrored image = 1
  Number of CPU threads = 4
  Use CUDA = 1
  Distribution function for SOM update = unitygaussian
  Sigma = 0.7
  Damping factor = 0.05
  Maximum distance for SOM update = -1
  Use periodic boundary conditions = 0
  Random shuffle data input = 1

  CUDA Device Query...
  There are 2 CUDA devices.

  CUDA Device #0
  Major revision number:         6
  Minor revision number:         0
  Name:                          Tesla P100-SXM2-16GB
  Total global memory:           17071734784
  Total shared memory per block: 49152
  Total registers per block:     65536
  Warp size:                     32
  Maximum memory pitch:          2147483647
  Maximum threads per block:     1024
  Maximum dimension 0 of block:  1024
  Maximum dimension 1 of block:  1024
  Maximum dimension 2 of block:  64
  Maximum dimension 0 of grid:   2147483647
  Maximum dimension 1 of grid:   65535
  Maximum dimension 2 of grid:   65535
  Clock rate:                    1480500
  Total constant memory:         65536
  Texture alignment:             512
  Concurrent copy and execution: Yes
  Number of multiprocessors:     56
  Kernel execution timeout:      No


  CUDA Device #1
  Major revision number:         6
  Minor revision number:         0
  Name:                          Tesla P100-SXM2-16GB
  Total global memory:           17071734784
  Total shared memory per block: 49152
  Total registers per block:     65536
  Warp size:                     32
  Maximum memory pitch:          2147483647
  Maximum threads per block:     1024
  Maximum dimension 0 of block:  1024
  Maximum dimension 1 of block:  1024
  Maximum dimension 2 of block:  64
  Maximum dimension 0 of grid:   2147483647
  Maximum dimension 1 of grid:   65535
  Maximum dimension 2 of grid:   65535
  Clock rate:                    1480500
  Total constant memory:         65536
  Texture alignment:             512
  Concurrent copy and execution: Yes
  Number of multiprocessors:     56
  Kernel execution timeout:      No

[=======>                                                              ] 10 % 2013.26 s
[==============>                                                       ] 20 % 4026.46 s
[=====================>                                                ] 30 % 6041.26 s
[============================>                                         ] 40 % 8057.02 s
[===================================>                                  ] 50 % 10086.3 s
[==========================================>                           ] 60 % 12121.4 s
[=================================================>                    ] 70 % 14162.4 s
[========================================================>             ] 80 % 16208.1 s
  Write final SOM to SOM_B3Circular_h15_w15_emu.bin ... done.

  Total time (hh:mm:ss): 04:30:09.776     (16209 s)

  Successfully finished. Have a nice day.
```

Whats strange for both is that they neither were killed nor experienced a fatal error. They just ended and successfully wrote out the SOM binary file. Inspecting both of these SOMs there are a set of neurons that are just blank, appearing to be completely zero. 

Whats even stranger is that the SOMs from the second training stage (those that seeded these failed SOMs) appears perfectly fine. 

I don't think the process of slurm job were canceled because in the same slurm script the mapping stage (subsequent to this failed training round) completed without issue. 

When building the image binary file I exclude all images that fail `np.sum(~np.isfinite(img)) > 0`, so all should have valid pixels.

Really unsure what to make of this. Oh, the 8x8 and 35x35 SOM seem to be fine with no issues. Any ideas or initial thoughts?

![EMU_Complex_EMU_Channel](https://user-images.githubusercontent.com/10543142/80490526-0fb66c00-8994-11ea-9128-3cff5efd226e.png)
![EMU_Complex_WISE_Channel](https://user-images.githubusercontent.com/10543142/80490539-1513b680-8994-11ea-80b1-8667640f8323.png)

**Comment by BerndDoser** [comment] 2020-04-28 15:45
Never saw such behavior. Is it reproducible?

**Comment by tjgalvin** [comment] 2020-04-29 03:34
I have never seen it either, and from what I know of the codebase don't see how it could happen. 

I reran the same script with the same data last night and all SOMs (except the 35x35 which is still training) came back perfectly normal as far as I can tell. A little perplexed about this. I did not have exclusive use the GPUs. Is it possible that exhausting the memory on a card (from other co-running jobs) would cause strange behavior like this?

**Comment by BerndDoser** [comment] 2020-04-29 07:14
A memory damage is possible if the GPU card is multiple occupied. We had this sort of problems with our first slurm configuration, where the GPUs were not correct assigned to the slurm job. In our current slurm configuration you have to register the number of GPUs which gives you exclusive access.

**Comment by BerndDoser** [comment] 2020-04-29 07:23
But it is still strange, because a GPU memory corruption should only affect the pixels. The iteration variable is not part of the GPU memory, so that it can not explain a premature exit of the training loop.

**Comment by tjgalvin** [comment] 2020-04-29 07:59
It is certainly strange. If I can end up recreating the issue I will let you know. 

I am a little unsure on the exact configuration of our slurm queue. I have some vague memory of options to provide exclusive use of a node for a job, so some type of sharing among multiple processes is possible. Whether this carries through to GPU jobs I am not sure...

**Comment by BerndDoser** [comment] 2020-04-29 08:12
I use `--gres=gpu:2` for slurm and then with `nvidea-smi` I only see the two registered GPUs. You can test it for example with an interactive job:

```
srun -p <queue> --gres=gpu:2 --exclusive --time=4:00:00 --pty bash
```

**Comment by tjgalvin** [comment] 2020-05-08 13:27
Since this initial posting I have been unable to replicate the issue. Such a strange one. The same code with different datasets have all come back without issue. Maybe closing this would be OK for the moment, and we can reopen it if we stumble across the exactly failure case.

**Comment by BerndDoser** [comment] 2020-05-08 21:15
Very calming. Thanks for giving the all-clear.

**Closed by BerndDoser** 2020-05-08 21:15 UTC
